openapi: 3.0.0
info:
  title: Codefusion API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://codefusion-frontend.web.app/
    description: Production server
  - url: http://localhost:8080
    description: Server for devel and testing purposes
paths:
  /users/{uuid}:
    get:
      summary: Returns an user info.
      description: Returns all the data of an user given his UUID
      tags: [ Users ]
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      responses:
        '200':    # status code
          description: User data
          content:
            application/json:
              schema:   # response body
                $ref: '#/components/schemas/userSchema'

  /users/signUp:
    post:
      summary: Creates a new user.
      tags: [ Users ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userSchema'
      responses:
        200:
          description: User has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userSchema'
        400:
          description: Incorrect request
        500:
          description: Server internal error

  /users/{uuid}/deleteUser:
    delete:
      summary: Deletes an user.
      description: Deletes all data of an user given his UUID
      tags: [ Users ]
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      responses:
        '200': # status code
          description: User data
          content:
            application/json:
              schema: # response body
                $ref: '#/components/schemas/userSchema'

components:
  schemas:
    userSchema:
      allOf:
        - type: object
          properties:
            userName:
              type: string
              example: "John"
            email:
              type: string
              example: "mail@domain.com"
            password:
              type: string
              example: "123456"
          required:
            - userName
            - email
            - password